services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: user
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - mynetwork

  app:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    container_name: user-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/user
      USER_DB: root
      PASS_DB: root
    ports:
      - "8081:8080"
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
