name: Pipeline to SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Maven packages cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Build project
        run: mvn clean compile

      - name: Run test and coverage report
        run: mvn test jacoco:report

      - name: Analyze with Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=EstudosMicroservices_user-entity \
            -Dsonar.branch.name=main