name: Pipeline to SonarCloud with Artifact

on:
  push:
    branches:
      - main
      - developer
  pull_request:
    branches:
      - main
      - developer
    types:
      - opened
      - synchronize

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: user
        ports:
          - 3308:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Somente local com Act-tool.
      - name: Install Maven (local only with ACT tool)
        if: ${{ env.ACT }}
        run: |
          apt-get update
          apt-get install -y maven

      - name: Setup JDK, Maven and Cache
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Build, Test, Analyze and Package
        id: build_step
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3308/user
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # O comando 'mvn' agora será encontrado
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=EstudosMicroservices_user-entity  \
            -Dsonar.branch.name=main

      - name: Upload Build Artifact
        if: ${{ !env.ACT }} # Somente em Github Actions.
        uses: actions/upload-artifact@v4
        with:
          name: java-package
          path: target/*.jar